version: '3.5'

services:
  deatabase:
    image: mongo:4.4.4
    container_name: io-database
    volumes:
      - io-database-vol:/data/db
    ports:
      - 27017:27017
  io-backend:
    container_name: io-backend
    build:
      context: .
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - spring.data.mongodb.uri=mongodb://host.docker.internal:27017/io

volumes:
  io-database-vol:
    name: io-database-vol