version: '3.5'

services:

  sample:
    container_name: io-webapp
    build:
      context: .
      args:
        - REACT_APP_BACKEND_URL=http://host.docker.internal:8080
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:8080
    environment:
      - CHOKIDAR_USEPOLLING=true