POST http://localhost:8080/quiz
Content-Type: application/json

{
  "questions": [
    {
      "content": "pytanie otwarte"
    },
    {
      "content": "pytanie zamknięte",
      "answers": [
        {
          "text": "dobra",
          "correct": true
        },
        {
          "text": "zła",
          "correct": false
        }
      ]
    }
  ]
}

###